### ISSUE TITLE
Reloading the leaderboard causes a nuxt error if the page is open on another browser/tab/device

### ISSUE THREAD

**Issue by lakner** [albert2804/transcendence#115]
<img width="880" alt="Screen Shot 2024-02-18 at 10 57 16 PM" src="https://github.com/albert2804/transcendence/assets/2691827/95109195-2301-4e9b-8ad8-64f1d4d2f9c6">

**Comment by albert2804** [comment]
Error: TypeError: Failed to parse URL from /endpoint/user/get_all_users?attributes=username,alias,num_games_played,num_games_won,mmr
when relading the page, i get this message. Invalid URL
<img width="801" alt="Screen Shot 2024-02-26 at 4 34 07 PM" src="https://github.com/albert2804/transcendence/assets/29372860/189543a1-5c90-4f9a-bb64-8bc05e64ade6">

**Comment by lakner** [comment]
I can't seem to reproduce this anymore - do you remember how you triggered this @albert2804 ?

**Comment by albert2804** [comment]
when reloading the leaderboard, but I didnt look into it so far. Its from the frontend container

**Comment by albert2804** [comment]
@lakner

**Comment by lakner** [comment]
Duplicated by #189
