### ISSUE TITLE
Tournament - announce the next fight

### ISSUE THREAD

**Issue by lakner** [albert2804/transcendence#133]
Subject: 
There must be a matchmaking system: the tournament system organize the
matchmaking of the participants, and announce the next fight.

**Comment by phipno** [comment]
one player sends the tournament game invite and the other one needs to accept it, it is written in the chat to which tournament game your were invited too.

Still there is no update over the chat atleast when a game in your tournament is finished and you are next to play

**Comment by Kathinka42** [comment]
solved with notification banner pull request
