### ISSUE TITLE
Game - ball is in egg shape

### ISSUE THREAD

**Issue by Kathinka42** [albert2804/transcendence#164]
When not playing in fullscreen mode, ball has egg shape

**Comment by Tilmanfs95** [comment]
Since the ea6723fb9fab467af388d0528a171a706b004d2d commit, the Gamefields height gets resized to the window height.
Ideally the GameField should have a format of 2/1 to have a round ball.
But now therefore the Gamefield fills the whole screen.

**Comment by Tilmanfs95** [comment]
oh it was in commit dcc25ab ;)
