### ISSUE TITLE
error log after uploading new profile pic

### ISSUE THREAD

**Issue by Tilmanfs95** [albert2804/transcendence#237]
Error fetching user profile pic: TypeError: NetworkError when attempting to fetch resource. [SettingsPic.vue:44:13](https://localhost/_nuxt/components/settings/SettingsPic.vue)
    NuxtJS 37

**Comment by albert2804** [comment]
i will look into this

**Comment by albert2804** [comment]
couldnt replicate the error on my Linux VM
