### ISSUE TITLE
Task List 09.02.24

### ISSUE THREAD

**Issue by phipno** [albert2804/transcendence#56]
**IMPORTANT**
- [x] #72
- [x] #73
- [x] #74
- [x] #75
- [x] #76
- [x] #77
- [x] #78

**less important**
- [x] #79
- [x] #80
- [x] #81
- [x] Multiple Players -> games with 4 Players,  refereeing to (https://github.com/albert2804/transendence/issues/50)
- [x] #82

![Uploading Screen Shot 2024-02-09 at 5.05.42 PM.png…]()

**Comment by phipno** [comment]
- [ ] asd

**Comment by Kathinka42** [comment]
Bots and multiplayer modes not implemented
