### ISSUE TITLE
Problems with reload button

### ISSUE THREAD

**Issue by albert2804** [albert2804/transcendence#90]
When refreshing the page, data in the backend gets lost.

**Comment by Tilmanfs95** [comment]
Which data?

**Comment by Tilmanfs95** [comment]
If you mean the data for the leaderboard, I think it is the same mistake like in Issue #92

**Comment by albert2804** [comment]
all data which gets saved to the database i think

**Comment by albert2804** [comment]
sorry didnt see the answer the last days
