### ISSUE TITLE
Add Error banner or something similar so backend errors can be displayed on the frontend

### ISSUE THREAD

**Issue by lakner** [albert2804/transcendence#94]
Something like this

<template>
  <div>
    <b-alert variant="danger" v-if="errorMessage" dismissible @dismissed="errorMessage = null">
      {{ errorMessage }}
    </b-alert>
    
  </div>
</template>

+ some javascript to read these errors

**Comment by lakner** [comment]
Incomplete, I'm fixing the issue with the login card
Todo:
- anything that can be changed in settings (profile pic, alias)

**Comment by Kathinka42** [comment]
issue fixed along with issue #137
